// Copy dell'email post-registrazione Eventbrite, per locale.
// Contratto congelato: AttendeeEmailCopy (lib/attendeeEmailTypes.ts).
// Stesso registro linguistico gia stabilito in lib/eventbriteConfirmation.ts
// (CONFIRMATION_COPY) per ogni locale: tu/voi, du/Sie, informale curato.
// Placeholder letterali da preservare: {event} {name} {phone}.
import type { AttendeeEmailCopy } from './attendeeEmailTypes';
import { enabledLocaleCodes, type LocaleCode } from './i18n/locales';

export const ATTENDEE_EMAIL_COPY: Record<LocaleCode, AttendeeEmailCopy> = {
  en: {
    subject: 'You’re on the list — {event}',
    greeting: 'Hi {name},',
    greetingNoName: 'Hi there,',
    intro: 'Your registration for {event} has been received — here are the details and how to secure your spot.',
    detailsHeading: 'Event details',
    whatsappCta: 'Questions or table bookings? Message us on WhatsApp at {phone}.',
    unsubscribeLabel: 'Unsubscribe',
    whyReceiving: 'You’re receiving this email because you registered for this event on Eventbrite. Sent by Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'You’re unsubscribed',
    unsubscribeDoneBody: 'You won’t receive these emails again. To turn them back on, message us on WhatsApp.',
    orderLabel: 'Order',
    ticketTypeLabel: 'Registration type',
    guestsLabel: 'Guests',
    registeredOnLabel: 'Registered on',
  },
  it: {
    subject: 'Sei in lista — {event}',
    greeting: 'Ciao {name},',
    greetingNoName: 'Ciao,',
    intro: 'Abbiamo ricevuto la tua registrazione per {event}: ecco i dettagli e come assicurarti l’ingresso.',
    detailsHeading: 'Dettagli evento',
    whatsappCta: 'Per domande o prenotazioni tavolo, scrivici su WhatsApp al {phone}.',
    unsubscribeLabel: 'Disiscriviti',
    whyReceiving: 'Ricevi questa email perché ti sei registrato a questo evento su Eventbrite. Inviata da Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Disiscrizione completata',
    unsubscribeDoneBody: 'Non riceverai più queste email. Per riattivarle, scrivici su WhatsApp.',
    orderLabel: 'Ordine',
    ticketTypeLabel: 'Tipo di registrazione',
    guestsLabel: 'Persone',
    registeredOnLabel: 'Registrato il',
  },
  es: {
    subject: 'Ya estás en la lista — {event}',
    greeting: 'Hola {name},',
    greetingNoName: 'Hola,',
    intro: 'Hemos recibido tu inscripción para {event}: aquí tienes los detalles y cómo asegurar tu entrada.',
    detailsHeading: 'Detalles del evento',
    whatsappCta: '¿Preguntas o reservas de mesa? Escríbenos por WhatsApp al {phone}.',
    unsubscribeLabel: 'Darse de baja',
    whyReceiving: 'Recibes este correo porque te has registrado a este evento en Eventbrite. Enviado por Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Baja confirmada',
    unsubscribeDoneBody: 'No volverás a recibir estos correos. Para reactivarlos, escríbenos por WhatsApp.',
    orderLabel: 'Pedido',
    ticketTypeLabel: 'Tipo de registro',
    guestsLabel: 'Personas',
    registeredOnLabel: 'Registrado el',
  },
  fr: {
    subject: 'Vous êtes sur la liste — {event}',
    greeting: 'Bonjour {name},',
    greetingNoName: 'Bonjour,',
    intro: 'Nous avons bien reçu votre inscription pour {event} : voici les détails et comment garantir votre place.',
    detailsHeading: 'Détails de l’événement',
    whatsappCta: 'Une question ou une réservation de table ? Écrivez-nous sur WhatsApp au {phone}.',
    unsubscribeLabel: 'Se désinscrire',
    whyReceiving: 'Vous recevez cet email car vous vous êtes inscrit à cet événement sur Eventbrite. Envoyé par Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Désinscription confirmée',
    unsubscribeDoneBody: 'Vous ne recevrez plus ces emails. Pour les réactiver, écrivez-nous sur WhatsApp.',
    orderLabel: 'Commande',
    ticketTypeLabel: 'Type d’inscription',
    guestsLabel: 'Personnes',
    registeredOnLabel: 'Inscription le',
  },
  de: {
    subject: 'Du bist auf der Liste — {event}',
    greeting: 'Hallo {name},',
    greetingNoName: 'Hallo,',
    intro: 'Deine Anmeldung für {event} ist eingegangen — hier sind die Details und wie du dir deinen Platz sicherst.',
    detailsHeading: 'Veranstaltungsdetails',
    whatsappCta: 'Fragen oder Tischreservierungen? Schreib uns auf WhatsApp an {phone}.',
    unsubscribeLabel: 'Abmelden',
    whyReceiving: 'Du erhältst diese E-Mail, weil du dich für diese Veranstaltung auf Eventbrite registriert hast. Gesendet von Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Abmeldung bestätigt',
    unsubscribeDoneBody: 'Du erhältst diese E-Mails nicht mehr. Um sie zu reaktivieren, schreib uns auf WhatsApp.',
    orderLabel: 'Bestellung',
    ticketTypeLabel: 'Registrierungsart',
    guestsLabel: 'Personen',
    registeredOnLabel: 'Registriert am',
  },
  pt: {
    subject: 'Já estás na lista — {event}',
    greeting: 'Olá {name},',
    greetingNoName: 'Olá,',
    intro: 'Recebemos a tua inscrição para {event}: aqui tens os detalhes e como garantir o teu lugar.',
    detailsHeading: 'Detalhes do evento',
    whatsappCta: 'Dúvidas ou reservas de mesa? Escreve-nos no WhatsApp para {phone}.',
    unsubscribeLabel: 'Cancelar subscrição',
    whyReceiving: 'Recebes este email porque te registaste neste evento no Eventbrite. Enviado por Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Subscrição cancelada',
    unsubscribeDoneBody: 'Deixarás de receber estes emails. Para os reativar, escreve-nos no WhatsApp.',
    orderLabel: 'Encomenda',
    ticketTypeLabel: 'Tipo de registo',
    guestsLabel: 'Pessoas',
    registeredOnLabel: 'Registado em',
  },
  nl: {
    subject: 'Je staat op de lijst — {event}',
    greeting: 'Hoi {name},',
    greetingNoName: 'Hoi,',
    intro: 'We hebben je aanmelding voor {event} ontvangen — hier zijn de details en hoe je je plek zeker stelt.',
    detailsHeading: 'Evenementdetails',
    whatsappCta: 'Vragen of een tafel reserveren? Stuur ons een bericht op WhatsApp naar {phone}.',
    unsubscribeLabel: 'Afmelden',
    whyReceiving: 'Je ontvangt deze e-mail omdat je je voor dit evenement hebt aangemeld via Eventbrite. Verzonden door Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Afmelding bevestigd',
    unsubscribeDoneBody: 'Je ontvangt deze e-mails niet meer. Om ze weer te activeren, stuur ons een bericht op WhatsApp.',
    orderLabel: 'Bestelling',
    ticketTypeLabel: 'Aanmeldingstype',
    guestsLabel: 'Personen',
    registeredOnLabel: 'Aangemeld op',
  },
  ru: {
    subject: 'Вы в списке — {event}',
    greeting: 'Здравствуйте, {name},',
    greetingNoName: 'Здравствуйте,',
    intro: 'Мы получили вашу регистрацию на {event} — вот детали и как гарантированно попасть на мероприятие.',
    detailsHeading: 'Детали мероприятия',
    whatsappCta: 'Вопросы или бронирование столика? Напишите нам в WhatsApp на номер {phone}.',
    unsubscribeLabel: 'Отписаться',
    whyReceiving: 'Вы получаете это письмо, потому что зарегистрировались на это мероприятие через Eventbrite. Отправлено Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Отписка подтверждена',
    unsubscribeDoneBody: 'Вы больше не будете получать эти письма. Чтобы возобновить их, напишите нам в WhatsApp.',
    orderLabel: 'Заказ',
    ticketTypeLabel: 'Тип регистрации',
    guestsLabel: 'Гости',
    registeredOnLabel: 'Дата регистрации',
  },
  tr: {
    subject: 'Listedesiniz — {event}',
    greeting: 'Merhaba, {name},',
    greetingNoName: 'Merhaba,',
    intro: '{event} için kaydınızı aldık — işte detaylar ve yerinizi garantilemenin yolu.',
    detailsHeading: 'Etkinlik detayları',
    whatsappCta: 'Sorularınız veya masa rezervasyonu için WhatsApp üzerinden {phone} numarasına yazın.',
    unsubscribeLabel: 'Abonelikten çıkın',
    whyReceiving: 'Bu e-postayı, bu etkinliğe Eventbrite üzerinden kaydolduğunuz için alıyorsunuz. Nightlife Milan (nightlifemilan.com) tarafından gönderildi.',
    unsubscribeDoneTitle: 'Abonelik iptal edildi',
    unsubscribeDoneBody: 'Bu e-postaları artık almayacaksınız. Tekrar almak için WhatsApp üzerinden bize yazın.',
    orderLabel: 'Sipariş',
    ticketTypeLabel: 'Kayıt türü',
    guestsLabel: 'Kişi sayısı',
    registeredOnLabel: 'Kayıt tarihi',
  },
  zh: {
    subject: '您已在名单中 — {event}',
    greeting: '{name}，您好，',
    greetingNoName: '您好，',
    intro: '我们已收到您对{event}的登记，以下是详情以及如何确保您的名额。',
    detailsHeading: '活动详情',
    whatsappCta: '如有疑问或需预订卡座，请通过WhatsApp联系我们：{phone}。',
    unsubscribeLabel: '取消订阅',
    whyReceiving: '您收到此邮件是因为您通过Eventbrite登记了此活动。发件方：Nightlife Milan（nightlifemilan.com）。',
    unsubscribeDoneTitle: '已取消订阅',
    unsubscribeDoneBody: '您将不再收到此类邮件。如需重新开启，请通过WhatsApp联系我们。',
    orderLabel: '订单',
    ticketTypeLabel: '登记类型',
    guestsLabel: '人数',
    registeredOnLabel: '登记日期',
  },
  ar: {
    subject: 'أنت على القائمة — {event}',
    greeting: 'مرحبًا {name}،',
    greetingNoName: 'مرحبًا،',
    intro: 'تم استلام تسجيلك في {event}، وفيما يلي التفاصيل وكيفية تأكيد مكانك.',
    detailsHeading: 'تفاصيل الفعالية',
    whatsappCta: 'لأي استفسار أو حجز طاولة، راسلنا عبر واتساب على {phone}.',
    unsubscribeLabel: 'إلغاء الاشتراك',
    whyReceiving: 'تصلك هذه الرسالة لأنك سجّلت في هذه الفعالية عبر Eventbrite. أُرسلت من Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'تم إلغاء الاشتراك',
    unsubscribeDoneBody: 'لن تصلك هذه الرسائل بعد الآن. لإعادة تفعيلها، راسلنا عبر واتساب.',
    orderLabel: 'الطلب',
    ticketTypeLabel: 'نوع التسجيل',
    guestsLabel: 'عدد الأشخاص',
    registeredOnLabel: 'تاريخ التسجيل',
  },
  bg: {
    subject: 'Вие сте в списъка — {event}',
    greeting: 'Здравейте, {name},',
    greetingNoName: 'Здравейте,',
    intro: 'Получихме регистрацията ви за {event} — ето детайлите и как да си гарантирате мястото.',
    detailsHeading: 'Детайли за събитието',
    whatsappCta: 'За въпроси или резервация на маса, пишете ни в WhatsApp на {phone}.',
    unsubscribeLabel: 'Отписване',
    whyReceiving: 'Получавате този имейл, защото се регистрирахте за това събитие в Eventbrite. Изпратено от Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Отписването е потвърдено',
    unsubscribeDoneBody: 'Няма да получавате повече тези имейли. За да ги активирате отново, пишете ни в WhatsApp.',
    orderLabel: 'Поръчка',
    ticketTypeLabel: 'Вид регистрация',
    guestsLabel: 'Гости',
    registeredOnLabel: 'Дата на регистрация',
  },
  hr: {
    subject: 'Na popisu ste — {event}',
    greeting: 'Pozdrav, {name},',
    greetingNoName: 'Pozdrav,',
    intro: 'Zaprimili smo vašu prijavu za {event} — u nastavku su detalji i kako osigurati svoje mjesto.',
    detailsHeading: 'Detalji događaja',
    whatsappCta: 'Za pitanja ili rezervaciju stola pišite nam na WhatsApp na {phone}.',
    unsubscribeLabel: 'Odjava',
    whyReceiving: 'Ovaj e-mail primate jer ste se prijavili na ovaj događaj putem Eventbritea. Poslao Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Odjava potvrđena',
    unsubscribeDoneBody: 'Više nećete primati ove e-mailove. Za ponovnu aktivaciju pišite nam na WhatsApp.',
    orderLabel: 'Narudžba',
    ticketTypeLabel: 'Vrsta prijave',
    guestsLabel: 'Osobe',
    registeredOnLabel: 'Datum prijave',
  },
  cs: {
    subject: 'Jste na seznamu — {event}',
    greeting: 'Dobrý den, {name},',
    greetingNoName: 'Dobrý den,',
    intro: 'Vaši registraci na {event} jsme přijali — zde jsou podrobnosti a jak si zajistit místo.',
    detailsHeading: 'Podrobnosti akce',
    whatsappCta: 'S dotazy nebo rezervací stolu nám napište na WhatsApp na {phone}.',
    unsubscribeLabel: 'Odhlásit se',
    whyReceiving: 'Tento e-mail dostáváte, protože jste se na tuto akci zaregistrovali přes Eventbrite. Odesláno Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Odhlášení potvrzeno',
    unsubscribeDoneBody: 'Tyto e-maily už nebudete dostávat. Pro jejich obnovení nám napište na WhatsApp.',
    orderLabel: 'Objednávka',
    ticketTypeLabel: 'Typ registrace',
    guestsLabel: 'Osoby',
    registeredOnLabel: 'Datum registrace',
  },
  da: {
    subject: 'Du er på listen — {event}',
    greeting: 'Hej {name},',
    greetingNoName: 'Hej,',
    intro: 'Vi har modtaget din tilmelding til {event} — her er detaljerne, og hvordan du sikrer din plads.',
    detailsHeading: 'Detaljer om arrangementet',
    whatsappCta: 'Spørgsmål eller bordreservation? Skriv til os på WhatsApp på {phone}.',
    unsubscribeLabel: 'Afmeld',
    whyReceiving: 'Du modtager denne e-mail, fordi du har tilmeldt dig dette arrangement på Eventbrite. Sendt af Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Afmelding bekræftet',
    unsubscribeDoneBody: 'Du modtager ikke længere disse e-mails. For at genaktivere dem, så skriv til os på WhatsApp.',
    orderLabel: 'Ordre',
    ticketTypeLabel: 'Tilmeldingstype',
    guestsLabel: 'Personer',
    registeredOnLabel: 'Tilmeldt den',
  },
  et: {
    subject: 'Sa oled nimekirjas — {event}',
    greeting: 'Tere, {name},',
    greetingNoName: 'Tere,',
    intro: 'Saime kätte sinu registreerumise üritusele {event} — siin on üksikasjad ja kuidas oma koht kindlustada.',
    detailsHeading: 'Ürituse üksikasjad',
    whatsappCta: 'Küsimuste või lauabroneeringu korral kirjuta meile WhatsAppis numbril {phone}.',
    unsubscribeLabel: 'Tellimuse lõpetamine',
    whyReceiving: 'Saad selle e-kirja, kuna registreerusid sellele üritusele Eventbrite’i kaudu. Saatja Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Tellimus on lõpetatud',
    unsubscribeDoneBody: 'Sa ei saa enam neid e-kirju. Nende taasaktiveerimiseks kirjuta meile WhatsAppis.',
    orderLabel: 'Tellimus',
    ticketTypeLabel: 'Registreerimise tüüp',
    guestsLabel: 'Külaliste arv',
    registeredOnLabel: 'Registreerimise kuupäev',
  },
  fi: {
    subject: 'Olet listalla — {event}',
    greeting: 'Hei, {name},',
    greetingNoName: 'Hei,',
    intro: 'Ilmoittautumisesi tapahtumaan {event} on vastaanotettu — tässä ovat tiedot ja ohjeet paikkasi varmistamiseen.',
    detailsHeading: 'Tapahtuman tiedot',
    whatsappCta: 'Kysymyksiä tai pöytävarauksia? Kirjoita meille WhatsAppissa numeroon {phone}.',
    unsubscribeLabel: 'Peruuta tilaus',
    whyReceiving: 'Saat tämän sähköpostin, koska ilmoittauduit tähän tapahtumaan Eventbriten kautta. Lähettäjä Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Tilaus peruutettu',
    unsubscribeDoneBody: 'Et enää saa näitä sähköposteja. Ottaaksesi ne uudelleen käyttöön, kirjoita meille WhatsAppissa.',
    orderLabel: 'Tilaus',
    ticketTypeLabel: 'Ilmoittautumistyyppi',
    guestsLabel: 'Henkilömäärä',
    registeredOnLabel: 'Ilmoittautumispäivä',
  },
  el: {
    subject: 'Είστε στη λίστα — {event}',
    greeting: 'Γεια σας, {name},',
    greetingNoName: 'Γεια σας,',
    intro: 'Λάβαμε την εγγραφή σας για την εκδήλωση {event} — ακολουθούν οι λεπτομέρειες και το πώς θα εξασφαλίσετε τη θέση σας.',
    detailsHeading: 'Λεπτομέρειες εκδήλωσης',
    whatsappCta: 'Για ερωτήσεις ή κράτηση τραπεζιού, γράψτε μας στο WhatsApp στο {phone}.',
    unsubscribeLabel: 'Διαγραφή',
    whyReceiving: 'Λαμβάνετε αυτό το email επειδή εγγραφήκατε σε αυτή την εκδήλωση μέσω του Eventbrite. Απεστάλη από τη Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Η διαγραφή επιβεβαιώθηκε',
    unsubscribeDoneBody: 'Δεν θα λαμβάνετε πλέον αυτά τα email. Για να τα ενεργοποιήσετε ξανά, γράψτε μας στο WhatsApp.',
    orderLabel: 'Παραγγελία',
    ticketTypeLabel: 'Τύπος εγγραφής',
    guestsLabel: 'Άτομα',
    registeredOnLabel: 'Ημερομηνία εγγραφής',
  },
  hu: {
    subject: 'Felkerültél a listára — {event}',
    greeting: 'Szia, {name},',
    greetingNoName: 'Szia,',
    intro: 'Megérkezett a jelentkezésed erre az eseményre: {event} — itt vannak a részletek, és hogyan biztosíthatod a helyed.',
    detailsHeading: 'Esemény részletei',
    whatsappCta: 'Kérdésed van, vagy asztalt foglalnál? Írj nekünk WhatsAppon a {phone} számon.',
    unsubscribeLabel: 'Leiratkozás',
    whyReceiving: 'Azért kapod ezt az e-mailt, mert regisztráltál erre az eseményre az Eventbrite-on. Küldő: Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Leiratkozás megerősítve',
    unsubscribeDoneBody: 'A továbbiakban nem kapod meg ezeket az e-maileket. Az újbóli aktiváláshoz írj nekünk WhatsAppon.',
    orderLabel: 'Rendelés',
    ticketTypeLabel: 'Regisztráció típusa',
    guestsLabel: 'Létszám',
    registeredOnLabel: 'Regisztráció dátuma',
  },
  ga: {
    subject: 'Tá tú ar an liosta — {event}',
    greeting: 'Dia duit, {name},',
    greetingNoName: 'Dia duit,',
    intro: 'Fuaireamar do chlárú don ócáid {event} — seo thíos na sonraí agus conas is féidir leat d’áit a chinntiú.',
    detailsHeading: 'Sonraí na hócáide',
    whatsappCta: 'Aon cheist agat nó má theastaíonn bord uait, scríobh chugainn ar WhatsApp chuig {phone}.',
    unsubscribeLabel: 'Díliostáil',
    whyReceiving: 'Faigheann tú an ríomhphost seo toisc gur chláraigh tú don ócáid seo ar Eventbrite. Seolta ag Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Díliostáil deimhnithe',
    unsubscribeDoneBody: 'Ní bhfaighidh tú na ríomhphoist seo a thuilleadh. Chun iad a athchur ar siúl, scríobh chugainn ar WhatsApp.',
    orderLabel: 'Ordú',
    ticketTypeLabel: 'Cineál Cláraithe',
    guestsLabel: 'Daoine',
    registeredOnLabel: 'Dáta Cláraithe',
  },
  lv: {
    subject: 'Jūs esat sarakstā — {event}',
    greeting: 'Sveiki, {name},',
    greetingNoName: 'Sveiki,',
    intro: 'Esam saņēmuši jūsu pieteikumu pasākumam {event} — šeit ir informācija un kā nodrošināt savu vietu.',
    detailsHeading: 'Pasākuma informācija',
    whatsappCta: 'Ja rodas jautājumi vai vēlaties rezervēt galdiņu, rakstiet mums WhatsApp uz {phone}.',
    unsubscribeLabel: 'Atrakstīties',
    whyReceiving: 'Jūs saņemat šo e-pastu, jo reģistrējāties šim pasākumam vietnē Eventbrite. Sūtītājs — Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Atrakstīšanās apstiprināta',
    unsubscribeDoneBody: 'Jūs vairs nesaņemsiet šos e-pastus. Lai tos atkal aktivizētu, rakstiet mums WhatsApp.',
    orderLabel: 'Pasūtījums',
    ticketTypeLabel: 'Reģistrācijas veids',
    guestsLabel: 'Personas',
    registeredOnLabel: 'Reģistrācijas datums',
  },
  lt: {
    subject: 'Jūs esate sąraše — {event}',
    greeting: 'Sveiki, {name},',
    greetingNoName: 'Sveiki,',
    intro: 'Gavome jūsų registraciją į {event} — štai informacija ir kaip užsitikrinti savo vietą.',
    detailsHeading: 'Renginio informacija',
    whatsappCta: 'Jei turite klausimų ar norite rezervuoti staliuką, rašykite mums WhatsApp numeriu {phone}.',
    unsubscribeLabel: 'Atsisakyti prenumeratos',
    whyReceiving: 'Šį laišką gaunate todėl, kad užsiregistravote į šį renginį per Eventbrite. Siuntėjas — Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Atsisakymas patvirtintas',
    unsubscribeDoneBody: 'Daugiau šių laiškų negausite. Norėdami juos vėl įjungti, rašykite mums WhatsApp.',
    orderLabel: 'Užsakymas',
    ticketTypeLabel: 'Registracijos tipas',
    guestsLabel: 'Žmonių skaičius',
    registeredOnLabel: 'Registracijos data',
  },
  mt: {
    subject: 'Int fuq il-lista — {event}',
    greeting: 'Merħba, {name},',
    greetingNoName: 'Merħba,',
    intro: 'Irċevejna r-reġistrazzjoni tiegħek għal {event} — hawn taħt issib id-dettalji u kif tista’ tiżgura postok.',
    detailsHeading: 'Dettalji tal-avveniment',
    whatsappCta: 'Għal mistoqsijiet jew biex tibbukkja mejda, ibgħatilna messaġġ fuq WhatsApp lil {phone}.',
    unsubscribeLabel: 'Iddiżabbona',
    whyReceiving: 'Qed tirċievi din l-email għax irreġistrajt għal dan l-avveniment fuq Eventbrite. Mibgħuta minn Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Iddiżabbonar ikkonfermat',
    unsubscribeDoneBody: 'Mhux se tibqa’ tirċievi dawn l-emails. Biex terġa’ tattivahom, ibgħatilna messaġġ fuq WhatsApp.',
    orderLabel: 'Ordni',
    ticketTypeLabel: 'Tip tar-Reġistrazzjoni',
    guestsLabel: 'Persuni',
    registeredOnLabel: 'Data tar-Reġistrazzjoni',
  },
  pl: {
    subject: 'Jesteś na liście — {event}',
    greeting: 'Cześć, {name},',
    greetingNoName: 'Cześć,',
    intro: 'Otrzymaliśmy Twoje zgłoszenie na {event} — oto szczegóły i sposób na zapewnienie sobie miejsca.',
    detailsHeading: 'Szczegóły wydarzenia',
    whatsappCta: 'Masz pytania lub chcesz zarezerwować stolik? Napisz do nas na WhatsApp pod numer {phone}.',
    unsubscribeLabel: 'Wypisz się',
    whyReceiving: 'Otrzymujesz tę wiadomość, ponieważ zarejestrowano Cię na to wydarzenie w Eventbrite. Wysłane przez Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Wypisanie potwierdzone',
    unsubscribeDoneBody: 'Nie będziesz już otrzymywać tych wiadomości. Aby je ponownie włączyć, napisz do nas na WhatsApp.',
    orderLabel: 'Zamówienie',
    ticketTypeLabel: 'Rodzaj rejestracji',
    guestsLabel: 'Osoby',
    registeredOnLabel: 'Data rejestracji',
  },
  ro: {
    subject: 'Ești pe listă — {event}',
    greeting: 'Salut, {name},',
    greetingNoName: 'Salut,',
    intro: 'Am primit înscrierea ta la {event} — iată detaliile și cum îți poți asigura locul.',
    detailsHeading: 'Detaliile evenimentului',
    whatsappCta: 'Pentru întrebări sau rezervări de masă, scrie-ne pe WhatsApp la {phone}.',
    unsubscribeLabel: 'Dezabonare',
    whyReceiving: 'Primești acest email deoarece te-ai înscris la acest eveniment pe Eventbrite. Trimis de Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Dezabonare confirmată',
    unsubscribeDoneBody: 'Nu vei mai primi aceste emailuri. Pentru a le reactiva, scrie-ne pe WhatsApp.',
    orderLabel: 'Comandă',
    ticketTypeLabel: 'Tipul înscrierii',
    guestsLabel: 'Persoane',
    registeredOnLabel: 'Data înscrierii',
  },
  sk: {
    subject: 'Ste na zozname — {event}',
    greeting: 'Dobrý deň, {name},',
    greetingNoName: 'Dobrý deň,',
    intro: 'Vašu registráciu na {event} sme prijali — tu sú podrobnosti a ako si zaistiť miesto.',
    detailsHeading: 'Podrobnosti podujatia',
    whatsappCta: 'S otázkami alebo rezerváciou stola nám napíšte na WhatsApp na {phone}.',
    unsubscribeLabel: 'Odhlásiť sa',
    whyReceiving: 'Tento e-mail dostávate, pretože ste sa zaregistrovali na toto podujatie cez Eventbrite. Odoslané Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Odhlásenie potvrdené',
    unsubscribeDoneBody: 'Tieto e-maily už nebudete dostávať. Pre ich opätovnú aktiváciu nám napíšte na WhatsApp.',
    orderLabel: 'Objednávka',
    ticketTypeLabel: 'Typ registrácie',
    guestsLabel: 'Osoby',
    registeredOnLabel: 'Dátum registrácie',
  },
  sl: {
    subject: 'Na seznamu ste — {event}',
    greeting: 'Pozdravljeni, {name},',
    greetingNoName: 'Pozdravljeni,',
    intro: 'Prejeli smo vašo prijavo za {event} — v nadaljevanju so podrobnosti in kako si zagotoviti mesto.',
    detailsHeading: 'Podrobnosti dogodka',
    whatsappCta: 'Za vprašanja ali rezervacijo mize nam pišite na WhatsApp na {phone}.',
    unsubscribeLabel: 'Odjava',
    whyReceiving: 'To sporočilo prejemate, ker ste se za ta dogodek prijavili prek Eventbrite. Poslal Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Odjava potrjena',
    unsubscribeDoneBody: 'Teh e-sporočil ne boste več prejemali. Za ponovno aktivacijo nam pišite na WhatsApp.',
    orderLabel: 'Naročilo',
    ticketTypeLabel: 'Vrsta prijave',
    guestsLabel: 'Osebe',
    registeredOnLabel: 'Datum prijave',
  },
  sv: {
    subject: 'Du är på listan — {event}',
    greeting: 'Hej {name},',
    greetingNoName: 'Hej,',
    intro: 'Vi har tagit emot din anmälan till {event} — här är detaljerna och hur du säkrar din plats.',
    detailsHeading: 'Evenemangsdetaljer',
    whatsappCta: 'Frågor eller bordsbokning? Skriv till oss på WhatsApp på {phone}.',
    unsubscribeLabel: 'Avregistrera',
    whyReceiving: 'Du får det här mejlet eftersom du anmälde dig till det här evenemanget via Eventbrite. Skickat av Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Avregistrering bekräftad',
    unsubscribeDoneBody: 'Du kommer inte längre att få dessa mejl. För att aktivera dem igen, skriv till oss på WhatsApp.',
    orderLabel: 'Order',
    ticketTypeLabel: 'Anmälningstyp',
    guestsLabel: 'Personer',
    registeredOnLabel: 'Anmäld den',
  },
  no: {
    subject: 'Du er på listen — {event}',
    greeting: 'Hei {name},',
    greetingNoName: 'Hei,',
    intro: 'Vi har mottatt påmeldingen din til {event} — her er detaljene og hvordan du sikrer plassen din.',
    detailsHeading: 'Detaljer om arrangementet',
    whatsappCta: 'Spørsmål eller bordreservasjon? Skriv til oss på WhatsApp på {phone}.',
    unsubscribeLabel: 'Meld av',
    whyReceiving: 'Du får denne e-posten fordi du meldte deg på dette arrangementet via Eventbrite. Sendt av Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Avmelding bekreftet',
    unsubscribeDoneBody: 'Du vil ikke lenger motta disse e-postene. For å aktivere dem igjen, skriv til oss på WhatsApp.',
    orderLabel: 'Bestilling',
    ticketTypeLabel: 'Påmeldingstype',
    guestsLabel: 'Personer',
    registeredOnLabel: 'Påmeldt den',
  },
  is: {
    subject: 'Þú ert á listanum — {event}',
    greeting: 'Hæ, {name},',
    greetingNoName: 'Hæ,',
    intro: 'Skráningin þín fyrir {event} hefur borist okkur — hér eru upplýsingarnar og hvernig þú tryggir þér pláss.',
    detailsHeading: 'Upplýsingar um viðburðinn',
    whatsappCta: 'Spurningar eða borðpantanir? Sendu okkur skilaboð á WhatsApp í {phone}.',
    unsubscribeLabel: 'Afskrá',
    whyReceiving: 'Þú færð þennan tölvupóst því þú skráðir þig á þennan viðburð á Eventbrite. Sent af Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Afskráning staðfest',
    unsubscribeDoneBody: 'Þú munt ekki lengur fá þessa tölvupósta. Til að virkja þá aftur skaltu senda okkur skilaboð á WhatsApp.',
    orderLabel: 'Pöntun',
    ticketTypeLabel: 'Tegund skráningar',
    guestsLabel: 'Gestir',
    registeredOnLabel: 'Skráningardagur',
  },
  uk: {
    subject: 'Вас додано до списку — {event}',
    greeting: 'Вітаємо, {name},',
    greetingNoName: 'Вітаємо,',
    intro: 'Ми отримали вашу реєстрацію на {event} — ось деталі та як гарантувати собі місце.',
    detailsHeading: 'Деталі заходу',
    whatsappCta: 'Якщо виникнуть запитання або потрібно забронювати столик, напишіть нам у WhatsApp на {phone}.',
    unsubscribeLabel: 'Відписатися',
    whyReceiving: 'Ви отримуєте цей лист, оскільки зареєструвалися на цей захід через Eventbrite. Надіслано Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Відписку підтверджено',
    unsubscribeDoneBody: 'Ви більше не отримуватимете ці листи. Щоб знову їх увімкнути, напишіть нам у WhatsApp.',
    orderLabel: 'Замовлення',
    ticketTypeLabel: 'Тип реєстрації',
    guestsLabel: 'Гості',
    registeredOnLabel: 'Дата реєстрації',
  },
  sq: {
    subject: 'Je në listë — {event}',
    greeting: 'Përshëndetje, {name},',
    greetingNoName: 'Përshëndetje,',
    intro: 'E morëm regjistrimin tënd për {event} — ja detajet dhe si ta sigurosh vendin tënd.',
    detailsHeading: 'Detajet e ngjarjes',
    whatsappCta: 'Për pyetje ose rezervim tavoline, na shkruaj në WhatsApp te {phone}.',
    unsubscribeLabel: 'Çregjistrohu',
    whyReceiving: 'E merr këtë email sepse je regjistruar për këtë ngjarje në Eventbrite. Dërguar nga Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Çregjistrimi u konfirmua',
    unsubscribeDoneBody: 'Nuk do të marrësh më këto emaile. Për t’i riaktivizuar, na shkruaj në WhatsApp.',
    orderLabel: 'Porosia',
    ticketTypeLabel: 'Lloji i regjistrimit',
    guestsLabel: 'Persona',
    registeredOnLabel: 'Data e regjistrimit',
  },
  sr: {
    subject: 'Na listi ste — {event}',
    greeting: 'Zdravo, {name},',
    greetingNoName: 'Zdravo,',
    intro: 'Primili smo vašu prijavu za {event} — u nastavku su detalji i kako da obezbedite svoje mesto.',
    detailsHeading: 'Detalji događaja',
    whatsappCta: 'Za pitanja ili rezervaciju stola, pišite nam na WhatsApp na {phone}.',
    unsubscribeLabel: 'Odjava',
    whyReceiving: 'Ovaj imejl dobijate zato što ste se prijavili za ovaj događaj preko Eventbrite-a. Poslao Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Odjava potvrđena',
    unsubscribeDoneBody: 'Više nećete dobijati ove imejlove. Da biste ih ponovo aktivirali, pišite nam na WhatsApp.',
    orderLabel: 'Narudžbina',
    ticketTypeLabel: 'Vrsta prijave',
    guestsLabel: 'Osobe',
    registeredOnLabel: 'Datum prijave',
  },
  bs: {
    subject: 'Na listi ste — {event}',
    greeting: 'Zdravo, {name},',
    greetingNoName: 'Zdravo,',
    intro: 'Primili smo vašu prijavu za {event} — u nastavku su detalji i kako osigurati svoje mjesto.',
    detailsHeading: 'Detalji događaja',
    whatsappCta: 'Za pitanja ili rezervaciju stola, pišite nam na WhatsApp na {phone}.',
    unsubscribeLabel: 'Odjava',
    whyReceiving: 'Ovaj email dobijate zato što ste se prijavili za ovaj događaj putem Eventbritea. Poslao Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Odjava potvrđena',
    unsubscribeDoneBody: 'Više nećete primati ove emailove. Da biste ih ponovo aktivirali, pišite nam na WhatsApp.',
    orderLabel: 'Narudžba',
    ticketTypeLabel: 'Vrsta prijave',
    guestsLabel: 'Osobe',
    registeredOnLabel: 'Datum prijave',
  },
  mk: {
    subject: 'Сте на листата — {event}',
    greeting: 'Здраво, {name},',
    greetingNoName: 'Здраво,',
    intro: 'Ја примивме вашата регистрација за {event} — еве ги деталите и како да си го обезбедите местото.',
    detailsHeading: 'Детали за настанот',
    whatsappCta: 'За прашања или резервација на маса, пишете ни на WhatsApp на {phone}.',
    unsubscribeLabel: 'Откажување на претплата',
    whyReceiving: 'Го добивате овој имејл затоа што се регистриравте за овој настан преку Eventbrite. Испратено од Nightlife Milan (nightlifemilan.com).',
    unsubscribeDoneTitle: 'Откажувањето е потврдено',
    unsubscribeDoneBody: 'Повеќе нема да ги добивате овие имејли. За да ги активирате повторно, пишете ни на WhatsApp.',
    orderLabel: 'Нарачка',
    ticketTypeLabel: 'Вид регистрација',
    guestsLabel: 'Лица',
    registeredOnLabel: 'Датум на регистрација',
  },
};

export function getAttendeeEmailCopy(locale: LocaleCode): AttendeeEmailCopy {
  const copy = ATTENDEE_EMAIL_COPY[locale];
  if (!copy) throw new Error(`Missing attendee email copy for ${locale}`);
  return copy;
}

export function validateAttendeeEmailCopyCoverage(): void {
  const missingLocales = enabledLocaleCodes.filter((locale) => !ATTENDEE_EMAIL_COPY[locale]);
  if (missingLocales.length > 0) throw new Error(`Missing attendee email copy: ${missingLocales.join(', ')}`);

  const emptyFields: string[] = [];
  for (const locale of enabledLocaleCodes) {
    const copy = ATTENDEE_EMAIL_COPY[locale];
    for (const [field, value] of Object.entries(copy)) {
      if (!value || !value.trim()) emptyFields.push(`${locale}.${field}`);
    }
  }
  if (emptyFields.length > 0) throw new Error(`Empty attendee email copy fields: ${emptyFields.join(', ')}`);
}
