import type { LocaleCode } from './i18n/locales';

export interface BadBunnyAriaEditorialCopy {
  eventName: string;
  independentNotice: string;
  performanceQuestion: string;
  targetLabel: string;
}

export const BAD_BUNNY_ARIA_EDITORIAL_COPY: Record<LocaleCode, BadBunnyAriaEditorialCopy> = {
  en: { eventName: 'Bad Bunny Independent After-Party', independentNotice: 'This is an independent after-party inspired by the concert night. Bad Bunny does not perform at Aria Club, and the event is not affiliated with the artist or the concert organiser.', performanceQuestion: 'Does Bad Bunny perform at Aria Club?', targetLabel: 'Post-concert crowd and entry' },
  it: { eventName: 'Bad Bunny After Party Indipendente', independentNotice: 'È un after-party indipendente ispirato alla notte del concerto. Bad Bunny non si esibisce all’Aria Club e l’evento non è affiliato all’artista né all’organizzazione del concerto.', performanceQuestion: 'Bad Bunny si esibisce all’Aria Club?', targetLabel: 'Pubblico post-concerto e ingresso' },
  es: { eventName: 'After Party independiente de Bad Bunny', independentNotice: 'Es un after party independiente inspirado en la noche del concierto. Bad Bunny no actúa en Aria Club y el evento no está afiliado al artista ni a la organización del concierto.', performanceQuestion: '¿Bad Bunny actúa en Aria Club?', targetLabel: 'Público posconcierto y acceso' },
  fr: { eventName: 'After-party indépendant Bad Bunny', independentNotice: 'Il s’agit d’un after-party indépendant inspiré par la soirée du concert. Bad Bunny ne se produit pas à l’Aria Club et l’événement n’est affilié ni à l’artiste ni à l’organisateur du concert.', performanceQuestion: 'Bad Bunny se produit-il à l’Aria Club ?', targetLabel: 'Public d’après-concert et entrée' },
  de: { eventName: 'Unabhängige Bad Bunny Afterparty', independentNotice: 'Dies ist eine unabhängige Afterparty, inspiriert von der Konzertnacht. Bad Bunny tritt nicht im Aria Club auf; die Veranstaltung ist weder mit dem Künstler noch mit dem Konzertveranstalter verbunden.', performanceQuestion: 'Tritt Bad Bunny im Aria Club auf?', targetLabel: 'Publikum nach dem Konzert und Einlass' },
  pt: { eventName: 'After-party independente de Bad Bunny', independentNotice: 'Este é um after-party independente inspirado na noite do concerto. Bad Bunny não atua no Aria Club e o evento não é afiliado ao artista nem à organização do concerto.', performanceQuestion: 'Bad Bunny atua no Aria Club?', targetLabel: 'Público pós-concerto e entrada' },
  nl: { eventName: 'Onafhankelijke Bad Bunny-afterparty', independentNotice: 'Dit is een onafhankelijke afterparty, geïnspireerd op de concertavond. Bad Bunny treedt niet op in Aria Club en het evenement is niet verbonden aan de artiest of de concertorganisator.', performanceQuestion: 'Treedt Bad Bunny op in Aria Club?', targetLabel: 'Publiek na het concert en toegang' },
  ru: { eventName: 'Независимое афтепати Bad Bunny', independentNotice: 'Это независимое афтепати, вдохновлённое вечером концерта. Bad Bunny не выступает в Aria Club, а мероприятие не связано с артистом или организатором концерта.', performanceQuestion: 'Выступает ли Bad Bunny в Aria Club?', targetLabel: 'Публика после концерта и вход' },
  tr: { eventName: 'Bağımsız Bad Bunny After-Party', independentNotice: 'Bu, konser gecesinden ilham alan bağımsız bir after-party’dir. Bad Bunny Aria Club’da sahne almaz; etkinliğin sanatçı veya konser organizatörüyle bağlantısı yoktur.', performanceQuestion: 'Bad Bunny Aria Club’da sahne alıyor mu?', targetLabel: 'Konser sonrası kitle ve giriş' },
  zh: { eventName: 'Bad Bunny 独立演唱会后派对', independentNotice: '这是一个以演唱会之夜为灵感的独立派对。Bad Bunny 不会在 Aria Club 演出，本活动与艺人或演唱会主办方均无关联。', performanceQuestion: 'Bad Bunny 会在 Aria Club 演出吗？', targetLabel: '演唱会后人群与入场' },
  ar: { eventName: 'حفل ما بعد الحفل المستقل لـ Bad Bunny', independentNotice: 'هذا حفل مستقل بعد الحفل الموسيقي مستوحى من ليلة الحفل. لن يقدّم Bad Bunny عرضاً في Aria Club، والفعالية غير تابعة للفنان أو لمنظم الحفل.', performanceQuestion: 'هل يقدّم Bad Bunny عرضاً في Aria Club؟', targetLabel: 'جمهور ما بعد الحفل والدخول' },
  bg: { eventName: 'Независимо афтърпарти Bad Bunny', independentNotice: 'Това е независимо афтърпарти, вдъхновено от концертната вечер. Bad Bunny няма да участва в Aria Club и събитието не е свързано с изпълнителя или организатора на концерта.', performanceQuestion: 'Ще участва ли Bad Bunny в Aria Club?', targetLabel: 'Публика след концерта и вход' },
  hr: { eventName: 'Neovisni Bad Bunny after-party', independentNotice: 'Ovo je neovisni after-party nadahnut koncertnom večeri. Bad Bunny ne nastupa u Aria Clubu, a događaj nije povezan s izvođačem ni organizatorom koncerta.', performanceQuestion: 'Nastupa li Bad Bunny u Aria Clubu?', targetLabel: 'Publika nakon koncerta i ulaz' },
  cs: { eventName: 'Nezávislá afterparty Bad Bunny', independentNotice: 'Jde o nezávislou afterparty inspirovanou koncertním večerem. Bad Bunny v Aria Clubu nevystupuje a akce není spojena s umělcem ani pořadatelem koncertu.', performanceQuestion: 'Vystupuje Bad Bunny v Aria Clubu?', targetLabel: 'Publikum po koncertě a vstup' },
  da: { eventName: 'Uafhængig Bad Bunny-afterparty', independentNotice: 'Dette er en uafhængig afterparty inspireret af koncertaftenen. Bad Bunny optræder ikke på Aria Club, og arrangementet er ikke tilknyttet kunstneren eller koncertarrangøren.', performanceQuestion: 'Optræder Bad Bunny på Aria Club?', targetLabel: 'Publikum efter koncerten og adgang' },
  et: { eventName: 'Sõltumatu Bad Bunny järelpidu', independentNotice: 'See on kontserdiõhtust inspireeritud sõltumatu järelpidu. Bad Bunny ei esine Aria Clubis ning üritus ei ole seotud artisti ega kontserdikorraldajaga.', performanceQuestion: 'Kas Bad Bunny esineb Aria Clubis?', targetLabel: 'Kontserdijärgne publik ja sissepääs' },
  fi: { eventName: 'Riippumaton Bad Bunny -jatkobile', independentNotice: 'Tämä on konsertti-illasta inspiroitunut riippumaton jatkobile. Bad Bunny ei esiinny Aria Clubilla, eikä tapahtuma liity artistiin tai konsertin järjestäjään.', performanceQuestion: 'Esiintyykö Bad Bunny Aria Clubilla?', targetLabel: 'Konsertin jälkeinen yleisö ja sisäänpääsy' },
  el: { eventName: 'Ανεξάρτητο after-party Bad Bunny', independentNotice: 'Πρόκειται για ανεξάρτητο after-party εμπνευσμένο από τη βραδιά της συναυλίας. Ο Bad Bunny δεν εμφανίζεται στο Aria Club και η εκδήλωση δεν συνδέεται με τον καλλιτέχνη ή τον διοργανωτή της συναυλίας.', performanceQuestion: 'Εμφανίζεται ο Bad Bunny στο Aria Club;', targetLabel: 'Κοινό μετά τη συναυλία και είσοδος' },
  hu: { eventName: 'Független Bad Bunny afterparty', independentNotice: 'Ez egy, a koncert estéje által ihletett független afterparty. Bad Bunny nem lép fel az Aria Clubban, és az esemény nem áll kapcsolatban az előadóval vagy a koncert szervezőjével.', performanceQuestion: 'Fellép Bad Bunny az Aria Clubban?', targetLabel: 'Koncert utáni közönség és belépés' },
  ga: { eventName: 'Iarpháirtí neamhspleách Bad Bunny', independentNotice: 'Iarpháirtí neamhspleách é seo a spreag oíche na ceolchoirme. Ní bheidh Bad Bunny ag seinm in Aria Club agus níl an ócáid cleamhnaithe leis an ealaíontóir ná le heagraí na ceolchoirme.', performanceQuestion: 'An mbeidh Bad Bunny ag seinm in Aria Club?', targetLabel: 'Slua i ndiaidh na ceolchoirme agus iontráil' },
  lv: { eventName: 'Neatkarīga Bad Bunny pēcballīte', independentNotice: 'Šī ir neatkarīga pēcballīte, ko iedvesmojis koncerta vakars. Bad Bunny neuzstājas Aria Club, un pasākums nav saistīts ar mākslinieku vai koncerta rīkotāju.', performanceQuestion: 'Vai Bad Bunny uzstājas Aria Club?', targetLabel: 'Publika pēc koncerta un ieeja' },
  lt: { eventName: 'Nepriklausomas Bad Bunny vakarėlis po koncerto', independentNotice: 'Tai nepriklausomas vakarėlis, įkvėptas koncerto vakaro. Bad Bunny nepasirodo Aria Club, o renginys nėra susijęs su atlikėju ar koncerto organizatoriumi.', performanceQuestion: 'Ar Bad Bunny pasirodo Aria Club?', targetLabel: 'Publika po koncerto ir įėjimas' },
  mt: { eventName: 'After-party indipendenti ta’ Bad Bunny', independentNotice: 'Dan huwa after-party indipendenti ispirat mil-lejl tal-kunċert. Bad Bunny ma jdoqqx f’Aria Club u l-avveniment mhuwiex affiljat mal-artist jew mal-organizzatur tal-kunċert.', performanceQuestion: 'Bad Bunny se jdoqq f’Aria Club?', targetLabel: 'Udjenza wara l-kunċert u d-dħul' },
  pl: { eventName: 'Niezależne afterparty Bad Bunny', independentNotice: 'To niezależne afterparty inspirowane wieczorem koncertowym. Bad Bunny nie występuje w Aria Club, a wydarzenie nie jest powiązane z artystą ani organizatorem koncertu.', performanceQuestion: 'Czy Bad Bunny występuje w Aria Club?', targetLabel: 'Publiczność po koncercie i wejście' },
  ro: { eventName: 'After-party independent Bad Bunny', independentNotice: 'Acesta este un after-party independent inspirat de seara concertului. Bad Bunny nu cântă la Aria Club, iar evenimentul nu este afiliat artistului sau organizatorului concertului.', performanceQuestion: 'Bad Bunny cântă la Aria Club?', targetLabel: 'Public după concert și acces' },
  sk: { eventName: 'Nezávislá afterparty Bad Bunny', independentNotice: 'Ide o nezávislú afterparty inšpirovanú koncertným večerom. Bad Bunny v Aria Clube nevystupuje a podujatie nie je spojené s umelcom ani organizátorom koncertu.', performanceQuestion: 'Vystupuje Bad Bunny v Aria Clube?', targetLabel: 'Publikum po koncerte a vstup' },
  sl: { eventName: 'Neodvisni Bad Bunny after-party', independentNotice: 'To je neodvisni after-party, ki ga navdihuje koncertni večer. Bad Bunny ne nastopa v klubu Aria, dogodek pa ni povezan z izvajalcem ali organizatorjem koncerta.', performanceQuestion: 'Ali Bad Bunny nastopa v klubu Aria?', targetLabel: 'Občinstvo po koncertu in vstop' },
  sv: { eventName: 'Oberoende Bad Bunny-efterfest', independentNotice: 'Detta är en oberoende efterfest inspirerad av konsertkvällen. Bad Bunny uppträder inte på Aria Club och evenemanget är inte kopplat till artisten eller konsertarrangören.', performanceQuestion: 'Uppträder Bad Bunny på Aria Club?', targetLabel: 'Publik efter konserten och entré' },
  no: { eventName: 'Uavhengig Bad Bunny-etterfest', independentNotice: 'Dette er en uavhengig etterfest inspirert av konsertkvelden. Bad Bunny opptrer ikke på Aria Club, og arrangementet er ikke tilknyttet artisten eller konsertarrangøren.', performanceQuestion: 'Opptrer Bad Bunny på Aria Club?', targetLabel: 'Publikum etter konserten og inngang' },
  is: { eventName: 'Óháð Bad Bunny-eftirpartí', independentNotice: 'Þetta er óháð eftirpartí innblásið af tónleikakvöldinu. Bad Bunny kemur ekki fram á Aria Club og viðburðurinn tengist hvorki listamanninum né tónleikahaldaranum.', performanceQuestion: 'Kemur Bad Bunny fram á Aria Club?', targetLabel: 'Gestir eftir tónleika og inngangur' },
  uk: { eventName: 'Незалежне афтерпаті Bad Bunny', independentNotice: 'Це незалежне афтерпаті, натхнене вечором концерту. Bad Bunny не виступає в Aria Club, а подія не пов’язана з артистом або організатором концерту.', performanceQuestion: 'Чи виступає Bad Bunny в Aria Club?', targetLabel: 'Публіка після концерту та вхід' },
  sq: { eventName: 'After-party i pavarur Bad Bunny', independentNotice: 'Ky është një after-party i pavarur i frymëzuar nga nata e koncertit. Bad Bunny nuk performon në Aria Club dhe eventi nuk lidhet me artistin ose organizatorin e koncertit.', performanceQuestion: 'A performon Bad Bunny në Aria Club?', targetLabel: 'Publiku pas koncertit dhe hyrja' },
  sr: { eventName: 'Nezavisni Bad Bunny after-party', independentNotice: 'Ovo je nezavisni after-party inspirisan koncertnom večeri. Bad Bunny ne nastupa u Aria Clubu, a događaj nije povezan sa izvođačem ni organizatorom koncerta.', performanceQuestion: 'Da li Bad Bunny nastupa u Aria Clubu?', targetLabel: 'Publika posle koncerta i ulaz' },
  bs: { eventName: 'Nezavisni Bad Bunny after-party', independentNotice: 'Ovo je nezavisni after-party inspirisan koncertnom večeri. Bad Bunny ne nastupa u Aria Clubu, a događaj nije povezan s izvođačem ni organizatorom koncerta.', performanceQuestion: 'Da li Bad Bunny nastupa u Aria Clubu?', targetLabel: 'Publika nakon koncerta i ulaz' },
  mk: { eventName: 'Независно Bad Bunny афтерпарти', independentNotice: 'Ова е независно афтерпарти инспирирано од концертната вечер. Bad Bunny не настапува во Aria Club и настанот не е поврзан со артистот или организаторот на концертот.', performanceQuestion: 'Дали Bad Bunny настапува во Aria Club?', targetLabel: 'Публика по концертот и влез' },
};
