export const UNIVERSITY_PARTY_PT_SLUG = 'justme-tuesday-martedi-universitario';

export const universityPartyPt = {
  title: 'Just Me Milano - University Party | Terca, 14 de julho de 2026',
  target: 'Estudantes universitarios, Erasmus, grupos internacionais e jovens profissionais 18+',
  intro: [
    'Na terca-feira, 14 de julho de 2026, o Just Me Milano recebe a University Party no Parco Sempione, junto a Torre Branca. A noite foi pensada para estudantes internacionais, Erasmus e grupos que procuram aperitivo, jantar opcional, pista e mesas VIP no mesmo endereco.',
    'A experiencia comeca cedo com aperitivo buffet e cocktails. A partir das 22:00, o ritmo muda para uma pista com house, hip hop, hits comerciais, EDM e reggaeton, com a festa a seguir ate as 05:00. Para entrar sem incertezas, confirme guest list, bilhete ou mesa pelo WhatsApp da Nightlife Milan antes de sair.',
  ],
  dressCode: 'Elegante e cuidado. Para homens, calcas compridas sao obrigatorias; calcoes e roupa desportiva podem impedir a entrada. Leve documento de identificacao: o evento e 18+.',
  agenda: [
    ['19:30', 'Chegada, aperitivo buffet e cocktails premium'],
    ['20:30', 'Jantar opcional e acolhimento de grupos com reserva'],
    ['22:00', 'Abertura da pista e inicio da University Party'],
    ['00:00', 'Pico da noite: house, hip hop, hits, EDM e reggaeton'],
    ['03:00', 'Late-night clubbing e bottle service nas mesas VIP'],
    ['05:00', 'Encerramento previsto da pista'],
  ],
  programme: [
    ['Aperitivo e jantar', 'Comece no ritmo certo: buffet, cocktails e possibilidade de jantar antes da pista ganhar intensidade.'],
    ['University dancefloor', 'Uma selecao feita para um publico internacional: house, hip hop, pop hits, EDM e reggaeton ao longo da noite.'],
    ['Mesas e bottle service', 'Dance Floor Table e VIP Area para grupos que querem uma base no clube, garrafas e apoio da concierge.'],
  ],
  prices: [
    ['Early Bird', 'EUR 13 - aperitivo buffet e 2 bebidas, sujeito a disponibilidade'],
    ['Club + 2 Drinks', 'EUR 15 - entrada no clube e duas bebidas'],
    ['Dance Floor Table', 'A partir de EUR 200 - confirme inclusoes e posicao pelo WhatsApp'],
    ['VIP Area Table', 'A partir de EUR 960 - bottle service e area reservada'],
  ],
  faqs: [
    ['O que e a University Party no Just Me Milano?', 'E a noite universitaria de terca-feira no Just Me, em Sempione: aperitivo, jantar opcional, pista e mesas VIP ate tarde.'],
    ['Onde fica o Just Me Milano?', 'O Just Me fica no Parco Sempione, junto a Torre Branca. Cadorna, Cairoli e Lanza sao estacoes praticas para chegar.'],
    ['A que horas abre a University Party?', 'A experiencia comeca as 19:30 com aperitivo. A pista ganha ritmo a partir das 22:00 e segue ate as 05:00.'],
    ['Quanto custa o Early Bird?', 'O Early Bird custa EUR 13 e inclui aperitivo buffet mais duas bebidas, sujeito a disponibilidade e confirmacao.'],
    ['Quanto custa Club + 2 Drinks?', 'Club + 2 Drinks custa EUR 15 e inclui entrada no clube e duas bebidas depois da fase de aperitivo.'],
    ['Como reservar mesa VIP no Just Me?', 'Envie no WhatsApp +39 351 912 7047 o numero de pessoas, horario de chegada e budget. A equipa confirma a disponibilidade.'],
    ['Quanto custa uma mesa no Just Me Milano?', 'A Dance Floor Table comeca em EUR 200 e a VIP Area Table em EUR 960. O valor final depende da posicao e do grupo.'],
    ['Existe guest list para raparigas?', 'Pode haver guest list feminina conforme disponibilidade. Confirme antes de sair pelo WhatsApp para receber as condicoes validas.'],
    ['Qual e o dress code do Just Me?', 'O dress code e elegante. Homens precisam de calcas compridas; calcoes e roupa desportiva podem impedir a entrada.'],
    ['A entrada e 18+?', 'Sim. A University Party e 18+. Leve documento de identificacao valido porque a seguranca pode verificar a idade.'],
    ['Que musica toca na University Party?', 'A pista mistura house, hip hop, hits comerciais, EDM e reggaeton, num formato feito para estudantes e grupos internacionais.'],
    ['Posso jantar antes da festa?', 'Sim. Alem do aperitivo buffet, ha jantar opcional antes da pista abrir totalmente. Confirme a reserva com antecedencia.'],
    ['O Eventbrite e o bilhete real para entrar?', 'A pagina Eventbrite e um pedido de informacao ou reserva. Confirme o acesso por Xceed ou WhatsApp antes de chegar.'],
    ['Onde compro bilhetes oficiais?', 'Use o link Xceed ou fale com a Nightlife Milan no WhatsApp para bilhetes, guest list e mesas VIP.'],
    ['Como evitar fila no Just Me?', 'Chegue cedo e confirme bilhete, guest list ou mesa antes. Uma reserva validada evita duvidas quando o clube enche.'],
    ['Qual e a melhor hora para chegar?', 'Chegue as 19:30 para aperitivo; perto das 22:00 para clubbing. Grupos com mesa devem alinhar o horario no WhatsApp.'],
    ['O Just Me e bom para estudantes internacionais?', 'Sim. A University Party foi feita para estudantes, Erasmus e grupos internacionais que querem sair numa terca-feira em Milao.'],
    ['Posso organizar aniversario no Just Me?', 'Sim. Para aniversarios e grupos, uma Dance Floor Table ou VIP Area da um ponto fixo e facilita a entrada conjunta.'],
    ['Ha bottle service?', 'Sim. As mesas podem incluir bottle service conforme o pacote. Confirme garrafas, posicao e inclusoes antes de pagar.'],
    ['O Just Me fica perto da Torre Branca?', 'Sim. O clube fica junto a Torre Branca, dentro do Parco Sempione, uma referencia simples para taxi e chegada a pe.'],
    ['Como chegar de metro?', 'Cadorna, Cairoli e Lanza sao opcoes praticas. A partir delas, siga pelo Parco Sempione ate a entrada do Just Me.'],
    ['Ha reembolso se eu nao puder ir?', 'Bilhetes online normalmente nao sao reembolsaveis. Verifique a data e as condicoes do canal de compra antes de confirmar.'],
    ['A reserva pelo WhatsApp e paga?', 'A concierge confirma disponibilidade. O pagamento depende do bilhete, entrada ou mesa que for efetivamente escolhido.'],
    ['Que palavras ajudam a encontrar este evento?', 'Just Me Milano, University Party Milan, festa universitaria Milao, Tuesday night Milan, mesa VIP Milao e nightlife Sempione.'],
    ['Por que escolher o Just Me numa terca-feira?', 'Porque junta Sempione, aperitivo cedo, pista ate as 05:00, publico internacional, mesas VIP e concierge num unico plano.'],
  ],
} as const;
